In [26]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2


DATADIR = "C:/Users/PC PRO ULTRA RAPIDE/Desktop/Projects/artificial intelligence/ml/sign-lang/sign-lang-dataset/"

ALPHABETS = ["aleff", "ain"]

for alphabet in ALPHABETS:
    path = os.path.join(DATADIR, alphabet)
    for img in os.listdir(path):
        img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
        #plt.imshow(img_array, cmap="gray")
        #plt.show()

In [4]:
print(img_array)

[[101 101 100 ...  69  69  69]
 [ 85  85  84 ...  68  68  68]
 [ 90  88  84 ...  66  66  66]
 ...
 [ 18  16  13 ...  27  28  29]
 [ 25  21  20 ...  28  29  30]
 [ 26  23  23 ...  29  30  31]]


In [27]:
print(img_array.shape) # data set well shaped :)

(64, 64)


In [28]:
training_data = []

def create_training_data():
    for alphabet in ALPHABETS:
        path = os.path.join(DATADIR, alphabet)
        class_num = ALPHABETS.index(alphabet) # 0 for alif and 1 for ain
        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
                training_data.append([img_array, class_num])
            except Exception as e:
                pass

create_training_data()

In [29]:
print(len(training_data[0]))

2


In [30]:
import random

random.shuffle(training_data)

In [9]:
for sample in training_data:
    print(sample[1])

0
0
0
0
1
1
1
0
1
0
0
1
1
0
0
1
1
0
1
1
1
0
0
1
1
1
0
1
0
1
1
1
1
1
0
1
1
1
0
0
1
1
1
1
0
0
0
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
1
0
0
1
1
1
0
0
0
0
0
0
1
0
0
1
0
1
0
1
1
1
1
1
0
0
0
1
0
1
0
1
1
0
0
1
0
0
1
1
1
0
1
0
0
0
1
1
1
1
0
0
0
1
0
1
1
0
0
1
0
1
1
0
0
1
0
1
0
0
0
0
0
1
1
1
1
0
1
1
0
0
0
1
1
1
1
1
1
1
0
0
1
1
0
0
1
1
0
1
0
1
0
1
1
1
0
1
1
1
0
1
1
1
1
0
1
0
0
1
1
0
1
1
1
0
0
0
0
1
0
0
0
0
0
1
0
1
1
1
1
0
0
0
1
1
1
1
1
1
0
1
1
1
1
0
0
1
0
1
1
1
1
0
1
0
0
0
1
1
0
1
0
0
0
1
0
1
1
0
0
1
1
1
0
1
1
1
0
0
0
1
0
0
1
1
1
0
1
1
1
1
1
0
0
0
1
1
0
1
0
0
1
1
1
0
0
0
0
0
1
0
1
1
1
1
1
1
1
1
0
0
0
0
1
0
0
1
1
0
1
0
1
1
1
0
1
1
1
1
1
1
0
1
1
0
1
1
0
0
0
1
1
0
1
0
0
0
1
0
1
1
1
1
0
1
1
1
0
0
0
0
0
1
0
0
0
0
1
1
0
0
0
0
1
0
0
0
1
1
1
0
1
0
0
0
0
0
0
1
0
1
0
1
1
0
0
1
1
1
0
0
1
1
1
0
1
1
1
1
1
1
1
1
1
0
0
1
1
1
1
0
1
1
1
0
1
1
1
1
1
0
1
0
1
1
1
0
1
0
0
1
1
1
1
0
1
0
1
0
1
0
1
1
0
0
0
0
0
0
1
1
0
1
1
1
1
1
1
1
1
1
0
0
0
0
1
1
1
1
1
0
1
0
0
1
0
1
0
0
1
0
0
0
0
0
1
1
0
0
1
0
0
0
1
1
1
0
0
1
0
0
1
1
0


In [31]:
X = [] # features set
y = [] # label set

for feature, label in training_data:
    X.append(feature)
    y.append(label)
    
X = np.array(X).reshape(-1, 64, 64, 1)
y = np.array(y)

print(X.shape)

(3786, 64, 64, 1)


In [32]:
# Saving the data set for later use :)

import pickle

pickle_out = open("X.pickle", "wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle", "wb")
pickle.dump(y, pickle_out)
pickle_out.close()


In [33]:
# to read saved data with pickle

pickle_in = open("X.pickle", "rb")
X = pickle.load(pickle_in)
X[1]

array([[[227],
        [227],
        [227],
        ...,
        [157],
        [128],
        [135]],

       [[227],
        [227],
        [227],
        ...,
        [149],
        [143],
        [134]],

       [[227],
        [227],
        [227],
        ...,
        [138],
        [156],
        [136]],

       ...,

       [[181],
        [181],
        [181],
        ...,
        [140],
        [120],
        [ 95]],

       [[180],
        [180],
        [180],
        ...,
        [138],
        [127],
        [112]],

       [[180],
        [180],
        [180],
        ...,
        [131],
        [129],
        [130]]], dtype=uint8)